### ISSUE TITLE
Jedi 0.9.0 release

### ISSUE THREAD

**Issue by davidhalter** [davidhalter/jedi#566]
I will try to release Jedi in the next two days.

The only issues that I still want to tackle in this release are:

  - [ ] Improved virtualenv support #562 (possibly not be merged)
  - [x] ``open().read()`` doesn't work well. #412
  - [x] Change `er.wrap` to `evaluator.wrap`
  - [x] Fix full name issues #519
  - [x] Refactor the import logic to a more importlib similar way (like using sys.modules).
  - [x] https://github.com/davidhalter/jedi-vim/issues/377
  - [x] pr -> pt or tree
  - [x] #536

If there's something else that you really need or want in Jedi 0.9.0, please let me know. I would also be happy if a few people tried the current dev branch already. Thanks in advance!

~ Dave

Changelog:

- Integrated the parser of 2to3. This will make refactoring possible. It will
  also be possible to check for error messages (like compiling an AST would give)
  in the future.
- With the new parser, the evaluation also completely changed. It's now simpler
  and more readable.
- Completely rewritten REPL completion.
- Added ``jedi.names``, a command to do static analysis. Thanks to that
  sourcegraph guys for sponsoring this!
- Alpha version of the linter.

**Comment by davidhalter** [comment]
It's finished. I will now push it to PyPI. It took me a bit longer, because I ended up rewriting the whole import logic. The import logic looks now way more like Python's and has a `sys.modules` kind of cache as well.

**Comment by davidhalter** [comment]
Uploaded. (After a few more sith tests). Have fun using it :-)

It's definitely the best Jedi version, yet. :)

**Comment by asmeurer** [comment]
The release seems to work well for me so far (not much testing yet, though). 

I have a question, though. What is `jedi.names`? It is referenced in the changelog and the README, but I can't find it. Is it supposed to be a command, or a module, or what?

**Comment by davidhalter** [comment]
Is that good enough? http://jedi.readthedocs.org/en/latest/docs/plugin-api.html#jedi.api.names

**Comment by asmeurer** [comment]
I'm not clear how that is static analysis (at least any more than Jedi already is). Also, is this different from what was already there? I'm mainly a user of jedi via emacs-jedi, not the Python API, but I know that there has been [something](https://github.com/tkf/emacs-jedi-direx) that does what seems to me to be the same thing for some time. Can you explain what's new here, that couldn't be done before?

**Comment by davidhalter** [comment]
You're right. It's not a bit change.

IMO there are two reasons why I would call it an improvement:

1. It's now easier to do bulk calculations. Basically everything that `PySonar2` does is now easily possible: https://github.com/yinwang0/pysonar2. Before that was possible, too. However it wasn't easy to speed up, because you had to scan for names yourself and then call `jedi.goto_definitions` on it, which would flush the caches all the time. Now it should be fast and easy to use.
2. Not mentioned in the changelog, but you can now call `goto_definitions` and `goto_assignments` on a name found with `names` (or any other Jedi operation). This is basically a generalization of what we've had before, but it also makes things easier. There's also a few other new api details that make inspecting source code better.

Is that enough?
